language: node_js
node_js:
  - "node"
addons:
  postgresql: "11.1"
  apt:
    packages:
    - postgresql-11
env:
  global:
  - PGPORT=5433
before_script:
  -psql -c 'CREATE DATABASE expressSweaterWeather_test;' -U postgres
